#!/usr/bin/env bun
// ============================================================================
// Resume builder CLI.
//
// Usage:
//   resume-build --content <file.json> [options]
//
// Options:
//   --content <path>            Resume content JSON (required).
//   --theme <path|name>         Theme preset: a .json path, or a name resolved to
//                               themes/<name>.theme.json. Overrides content.theme.
//   --out <dir>                 Output directory (default: ./out).
//   --basename <name>           Output file base name (default: derived from name).
//   --one-pager                 Iteratively shrink spacing/margins/font (within
//                               ATS-safe floors) to fit one page; warns if it can't.
//   --no-pdf                    Skip PDF generation (docx only).
//   --keywords <comma,list>     Bold these terms wherever they appear in the Summary,
//                               Work-experience bullets, and Projects (case-insensitive,
//                               whole-term matching). Not stored in content/theme JSON —
//                               a render-time-only directive.
//   --schema <path>             Content schema (default: schema/resume.schema.json).
//   --theme-schema <path>       Theme schema (default: schema/theme.schema.json).
//   --strict                    Exit non-zero if any validation warnings occur.
//   --quiet                     Suppress warning output.
//   --version, -v               Print the version and exit.
//   --install-skill [name]      Install standalone skill(s) to BOTH
//                               ~/.claude/skills/<name>/ and ~/.copilot/skills/<name>/
//                               (standalone variant — invokes this binary directly,
//                               no repo). Omit <name> to install every bundled
//                               skill; see --help for the list of names.
//
// Behavior: validation is BEST-EFFORT — warnings are printed, defaults applied,
// obvious type mismatches coerced, and the resume is rendered from whatever
// content is present. It never hard-fails on content problems (unless --strict).
// ============================================================================

import { chmodSync, mkdirSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { homedir } from "node:os";
import { ResumeContent, Theme } from "./types";
import { validate, Warning, JsonSchema } from "./validate";
import { resolveTheme } from "./theme";
import { renderResume } from "./render";
import { packDocx, convertToPdf, countPdfPages, checkPdfToolchain } from "./pack";
import { autofitToSinglePage } from "./autofit";

// Statically imported (not read from disk) so `bun build --compile` embeds these
// directly into a standalone binary, where __dirname resolves to Bun's virtual
// filesystem rather than a real directory containing schema/themes/. `bun dist/cli.js`
// still reads the live files off disk first (see the Bun.file() existence checks
// below) — these are only the fallback for when that fails, i.e. inside the
// compiled binary.
import resumeSchemaBuiltin from "../schema/resume.schema.json";
import themeSchemaBuiltin from "../schema/theme.schema.json";
import corporateNavyBuiltin from "../themes/corporate-navy.theme.json";
import slateCompactBuiltin from "../themes/slate-compact.theme.json";
import pkg from "../package.json";
// Generated by scripts/generate-skill-bundle.ts (run automatically by `bun run
// build`/`bun run compile`) — every bundled skill's files, keyed by skill name, with
// each SKILL.md's repo/bun-specific instructions rewritten to invoke this binary
// directly. Not committed (gitignored); regenerate with `bun run prepare-skill` if
// missing.
import { SKILL_BUNDLES } from "./skill-bundle.generated";

// Bare `--theme <name>` resolves here first, before the fs-based lookup below.
// Adding a new theme preset needs a line here (+ a recompile) to be embedded.
const BUILTIN_THEMES: Record<string, Theme> = {
  "corporate-navy": corporateNavyBuiltin as Theme,
  "slate-compact": slateCompactBuiltin as Theme,
};

// Build an actionable "missing binary + how to install it" message, or null if
// the full PDF toolchain (LibreOffice + Poppler) is present.
function pdfToolchainWarning(toolchain: { soffice: boolean; pdfinfo: boolean }): string | null {
  const missing: string[] = [];
  if (!toolchain.soffice) missing.push("soffice (LibreOffice)");
  if (!toolchain.pdfinfo) missing.push("pdfinfo (Poppler)");
  if (!missing.length) return null;
  const hint = process.platform === "darwin"
    ? "brew install --cask libreoffice && brew install poppler"
    : process.platform === "linux"
    ? "sudo apt install libreoffice poppler-utils"
    : "see README.md Prerequisites section for install instructions";
  return `Missing ${missing.join(" and ")} on PATH — PDF output and autofit are skipped. Install: ${hint}`;
}

interface Args {
  content?: string; theme?: string; out: string; basename?: string;
  autofit: boolean; pdf: boolean; keywords: string[]; schema: string; themeSchema: string;
  strict: boolean; quiet: boolean;
}

async function parseArgs(argv: string[]): Promise<Args> {
  const here = __dirname;
  const root = resolve(here, "..");
  const a: Args = {
    out: resolve(process.cwd(), "out"),
    autofit: false, pdf: true, keywords: [],
    schema: join(root, "schema", "resume.schema.json"),
    themeSchema: join(root, "schema", "theme.schema.json"),
    strict: false, quiet: false,
  };
  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => argv[++i];
    switch (arg) {
      case "--content": a.content = next(); break;
      case "--theme": a.theme = next(); break;
      case "--out": a.out = resolve(next()); break;
      case "--basename": a.basename = next(); break;
      case "--one-pager": a.autofit = true; break;
      case "--no-pdf": a.pdf = false; break;
      case "--keywords": a.keywords = next().split(",").map((k) => k.trim()).filter(Boolean); break;
      case "--schema": a.schema = next(); break;
      case "--theme-schema": a.themeSchema = next(); break;
      case "--strict": a.strict = true; break;
      case "--quiet": a.quiet = true; break;
      case "-h": case "--help": printHelp(); process.exit(0); break;
      case "-v": case "--version": console.log(pkg.version); process.exit(0); break;
      case "--install-skill": {
        const peeked = argv[i + 1];
        const name = peeked && !peeked.startsWith("-") ? argv[++i] : undefined;
        await installSkill(name);
        process.exit(0);
        break;
      }
      default: console.error(`Unknown option: ${arg}`); printHelp(); process.exit(2); break;
    }
  }
  return a;
}

function printHelp() {
  console.log(`resume-build --content <file.json> [--theme <name|path>] [--out <dir>]
                   [--basename <name>] [--one-pager] [--no-pdf]
                   [--keywords <comma,list>] [--strict] [--quiet] [--version]
                   [--install-skill [name]]

Bundled skills (for --install-skill): ${Object.keys(SKILL_BUNDLES).join(", ")}`);
}

// Writes the embedded standalone variant of one (or every) bundled skill — invokes
// this binary directly, no repo — to both ~/.claude/skills/<name>/ and
// ~/.copilot/skills/<name>/, so either assistant picks it up. Always overwrites:
// re-running --install-skill is the update mechanism, no repo/build step, matches
// this CLI's non-interactive style elsewhere.
const SKILL_HOME_DIRS: Record<"claude" | "copilot", string> = {
  claude: ".claude",
  copilot: ".copilot",
};

async function installSkill(name?: string) {
  if (name && !(name in SKILL_BUNDLES)) {
    console.error(`Unknown skill: ${name}. Available: ${Object.keys(SKILL_BUNDLES).join(", ")}`);
    process.exit(2);
  }
  const names = name ? [name] : Object.keys(SKILL_BUNDLES);
  for (const skillName of names) {
    for (const [target, homeDir] of Object.entries(SKILL_HOME_DIRS) as [keyof typeof SKILL_HOME_DIRS, string][]) {
      const dest = join(homedir(), homeDir, "skills", skillName);
      const bundle = SKILL_BUNDLES[skillName][target];
      for (const [relPath, content] of Object.entries(bundle)) {
        const full = join(dest, relPath);
        mkdirSync(dirname(full), { recursive: true });
        await Bun.write(full, content);
        if (relPath.endsWith(".py")) chmodSync(full, 0o755);
      }
      console.log(`✓ Installed ${skillName} skill (standalone variant — uses tailor-resume directly, no repo) to:`);
      console.log(`  ${dest}`);
      console.log(`  Files: ${Object.keys(bundle).join(", ")}`);
    }
  }
}

async function readJson<T = unknown>(p: string): Promise<T> {
  return JSON.parse(await Bun.file(p).text()) as T;
}

async function resolveThemePath(themeArg: string | undefined, contentTheme: string | undefined, root: string): Promise<string | undefined> {
  const name = themeArg || contentTheme;
  if (!name) return undefined;
  if (name.endsWith(".json") && await Bun.file(name).exists()) return name;
  const byName = join(root, "themes", `${name}.theme.json`);
  if (await Bun.file(byName).exists()) return byName;
  if (await Bun.file(name).exists()) return name;
  return undefined;
}

function printWarnings(label: string, warnings: Warning[] | string[], quiet: boolean) {
  if (quiet || !warnings.length) return;
  console.warn(`\n⚠  ${label} (${warnings.length}):`);
  for (const w of warnings) {
    if (typeof w === "string") console.warn(`   - ${w}`);
    else console.warn(`   - ${w.path}: ${w.message}`);
  }
}

async function main() {
  const args = await parseArgs(process.argv);
  const root = resolve(__dirname, "..");

  if (!args.content) { console.error("Error: --content <file.json> is required."); printHelp(); process.exit(2); }
  if (!(await Bun.file(args.content).exists())) { console.error(`Error: content file not found: ${args.content}`); process.exit(2); }

  // --- load + validate content (best-effort) ---
  const content = await readJson<ResumeContent>(args.content);
  const contentSchema = await Bun.file(args.schema).exists() ? await readJson<JsonSchema>(args.schema) : resumeSchemaBuiltin;
  let contentWarnings: Warning[] = validate(contentSchema, content);
  printWarnings("Content validation warnings", contentWarnings, args.quiet);

  // --- load + validate theme (best-effort) ---
  // A bare theme name checks the embedded BUILTIN_THEMES first (works with no
  // filesystem access, e.g. inside a compiled binary); only names outside that map,
  // or an explicit --theme <path.json>, fall through to the fs-based lookup.
  const themeName = args.theme || content.theme;
  let themeRaw: Theme = {};
  let themeSource: string | undefined;
  if (themeName && BUILTIN_THEMES[themeName]) {
    themeRaw = BUILTIN_THEMES[themeName];
    themeSource = `${themeName} (built-in)`;
  } else {
    const themePath = await resolveThemePath(args.theme, content.theme, root);
    if (themePath) {
      themeRaw = await readJson<Theme>(themePath);
      themeSource = basename(themePath);
    } else if (themeName) {
      console.warn(`⚠  Theme "${themeName}" not found; using built-in defaults.`);
    }
  }
  if (themeSource) {
    const themeSchema = await Bun.file(args.themeSchema).exists() ? await readJson<JsonSchema>(args.themeSchema) : themeSchemaBuiltin;
    const themeWarnings = validate(themeSchema, themeRaw);
    printWarnings(`Theme validation warnings (${themeSource})`, themeWarnings, args.quiet);
    contentWarnings = contentWarnings.concat(themeWarnings);
  }
  const theme = resolveTheme(themeRaw);

  // --- output paths ---
  mkdirSync(args.out, { recursive: true });
  const base = args.basename || sanitize(content.basics?.name || "resume");
  const docxPath = join(args.out, `${base}.docx`);
  const runtimeWarnings: string[] = [];

  // --- PDF toolchain preflight (surface missing binaries up front, not just after a failed convert) ---
  const toolchain = (args.pdf || args.autofit) ? checkPdfToolchain() : { soffice: true, pdfinfo: true };
  const toolchainWarning = pdfToolchainWarning(toolchain);
  if (toolchainWarning && (args.pdf || args.autofit)) runtimeWarnings.push(toolchainWarning);

  // --- autofit (optional) ---
  let finalTheme = theme;
  if (args.autofit) {
    if (!args.pdf) {
      runtimeWarnings.push("--one-pager requires PDF rendering to measure pages; ignoring --no-pdf for measurement.");
    }
    const result = await autofitToSinglePage(content, theme, args.keywords);
    finalTheme = result.finalTheme;
    runtimeWarnings.push(...result.warnings);
    if (!args.quiet) {
      console.log(`\n▸ Autofit: ${result.fitted ? "fit to 1 page" : `stopped at ${result.pages} page(s)`} after ${result.iterations} iteration(s).`);
      console.log(`  final: body ${finalTheme.sizeBody}pt · margins ${finalTheme.margins.top}in · line-height ${finalTheme.lineHeight}`);
    }
  }

  // --- render + pack final docx ---
  const { doc, commentCount } = renderResume(content, finalTheme, args.keywords);
  const { commentIdsFixed } = await packDocx(doc, docxPath);
  if (!args.quiet) {
    console.log(`\n✓ DOCX: ${docxPath}`);
    if (commentCount) console.log(`  ${commentCount} flag comment(s)${commentIdsFixed ? `; repaired ${commentIdsFixed} marker id(s)` : ""}.`);
  }

  // --- pdf ---
  if (args.pdf) {
    const pdfPath = await convertToPdf(docxPath, args.out);
    const pages = await countPdfPages(pdfPath);
    if (await Bun.file(pdfPath).exists()) {
      if (!args.quiet) console.log(`✓ PDF:  ${pdfPath}${pages > 0 ? `  (${pages} page${pages === 1 ? "" : "s"})` : ""}`);
    } else if (!toolchainWarning) {
      // Toolchain looked present but conversion still failed — a different problem than a missing binary.
      runtimeWarnings.push("PDF conversion failed despite soffice/pdfinfo being on PATH; DOCX was still written. Check LibreOffice logs.");
    }
  }

  printWarnings("Runtime warnings", runtimeWarnings, args.quiet);

  const totalWarnings = contentWarnings.length + runtimeWarnings.length;
  if (args.strict && totalWarnings > 0) {
    console.error(`\n✗ --strict: ${totalWarnings} warning(s); exiting non-zero.`);
    process.exit(1);
  }
}

function sanitize(s: string): string {
  return s.replace(/[^\w.-]+/g, "_").replace(/^_+|_+$/g, "") || "resume";
}

main().catch((e) => { console.error("Fatal:", e); process.exit(1); });
