#!/usr/bin/env bun
// ============================================================================
// Resume builder CLI.
//
// Usage:
//   resume-build --content <file.json> [options]
//
// Options:
//   --content <path>            Resume content JSON (required).
//   --theme <path|name>         Theme preset: a .json path, or a name resolved to
//                               themes/<name>.theme.json. Overrides content.theme.
//   --out <dir>                 Output directory (default: ./out).
//   --basename <name>           Output file base name (default: derived from name).
//   --one-pager                 Iteratively shrink spacing/margins/font (within
//                               ATS-safe floors) to fit one page; warns if it can't.
//   --no-pdf                    Skip PDF generation (docx only).
//   --keywords <comma,list>     Bold these terms wherever they appear in the Summary,
//                               Work-experience bullets, and Projects (case-insensitive,
//                               whole-term matching). Not stored in content/theme JSON —
//                               a render-time-only directive.
//   --schema <path>             Content schema (default: schema/resume.schema.json).
//   --theme-schema <path>       Theme schema (default: schema/theme.schema.json).
//   --strict                    Exit non-zero if any validation warnings occur.
//   --quiet                     Suppress warning output.
//   --version, -v               Print the version and exit.
//   --install-skill             Install the jd-tailored-resume Claude Code skill to
//                               ~/.claude/skills/jd-tailored-resume/ (standalone
//                               variant — invokes this binary directly, no repo).
//
// Behavior: validation is BEST-EFFORT — warnings are printed, defaults applied,
// obvious type mismatches coerced, and the resume is rendered from whatever
// content is present. It never hard-fails on content problems (unless --strict).
// ============================================================================

import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { ResumeContent, Theme } from "./types";
import { validate, Warning } from "./validate";
import { resolveTheme } from "./theme";
import { renderResume } from "./render";
import { packDocx, convertToPdf, countPdfPages, checkPdfToolchain } from "./pack";
import { autofitToSinglePage } from "./autofit";

// Statically imported (not fs.readFileSync'd) so `bun build --compile` embeds these
// directly into a standalone binary, where __dirname resolves to Bun's virtual
// filesystem rather than a real directory containing schema/themes/. `bun dist/cli.js`
// still reads the live files off disk first (see fs.existsSync checks below) — these
// are only the fallback for when that fails, i.e. inside the compiled binary.
import resumeSchemaBuiltin from "../schema/resume.schema.json";
import themeSchemaBuiltin from "../schema/theme.schema.json";
import corporateNavyBuiltin from "../themes/corporate-navy.theme.json";
import slateCompactBuiltin from "../themes/slate-compact.theme.json";
import pkg from "../package.json";
// Generated by scripts/generate-skill-bundle.ts (run automatically by `bun run
// build`/`bun run compile`) — the jd-tailored-resume skill's files, with SKILL.md's
// repo/bun-specific instructions rewritten to invoke this binary directly. Not
// committed (gitignored); regenerate with `bun run prepare-skill` if missing.
import { SKILL_BUNDLE } from "./skill-bundle.generated";

// Bare `--theme <name>` resolves here first, before the fs-based lookup below.
// Adding a new theme preset needs a line here (+ a recompile) to be embedded.
const BUILTIN_THEMES: Record<string, Theme> = {
  "corporate-navy": corporateNavyBuiltin as Theme,
  "slate-compact": slateCompactBuiltin as Theme,
};

// Build an actionable "missing binary + how to install it" message, or null if
// the full PDF toolchain (LibreOffice + Poppler) is present.
function pdfToolchainWarning(toolchain: { soffice: boolean; pdfinfo: boolean }): string | null {
  const missing: string[] = [];
  if (!toolchain.soffice) missing.push("soffice (LibreOffice)");
  if (!toolchain.pdfinfo) missing.push("pdfinfo (Poppler)");
  if (!missing.length) return null;
  const hint = process.platform === "darwin"
    ? "brew install --cask libreoffice && brew install poppler"
    : process.platform === "linux"
    ? "sudo apt install libreoffice poppler-utils"
    : "see README.md Prerequisites section for install instructions";
  return `Missing ${missing.join(" and ")} on PATH — PDF output and autofit are skipped. Install: ${hint}`;
}

interface Args {
  content?: string; theme?: string; out: string; basename?: string;
  autofit: boolean; pdf: boolean; keywords: string[]; schema: string; themeSchema: string;
  strict: boolean; quiet: boolean;
}

function parseArgs(argv: string[]): Args {
  const here = __dirname;
  const root = path.resolve(here, "..");
  const a: Args = {
    out: path.resolve(process.cwd(), "out"),
    autofit: false, pdf: true, keywords: [],
    schema: path.join(root, "schema", "resume.schema.json"),
    themeSchema: path.join(root, "schema", "theme.schema.json"),
    strict: false, quiet: false,
  };
  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => argv[++i];
    switch (arg) {
      case "--content": a.content = next(); break;
      case "--theme": a.theme = next(); break;
      case "--out": a.out = path.resolve(next()); break;
      case "--basename": a.basename = next(); break;
      case "--one-pager": a.autofit = true; break;
      case "--no-pdf": a.pdf = false; break;
      case "--keywords": a.keywords = next().split(",").map((k) => k.trim()).filter(Boolean); break;
      case "--schema": a.schema = next(); break;
      case "--theme-schema": a.themeSchema = next(); break;
      case "--strict": a.strict = true; break;
      case "--quiet": a.quiet = true; break;
      case "-h": case "--help": printHelp(); process.exit(0);
      case "-v": case "--version": console.log(pkg.version); process.exit(0);
      case "--install-skill": installSkill(); process.exit(0);
      default: console.error(`Unknown option: ${arg}`); printHelp(); process.exit(2);
    }
  }
  return a;
}

function printHelp() {
  console.log(`resume-build --content <file.json> [--theme <name|path>] [--out <dir>]
                   [--basename <name>] [--one-pager] [--no-pdf]
                   [--keywords <comma,list>] [--strict] [--quiet] [--version]
                   [--install-skill]`);
}

// Writes the embedded jd-tailored-resume skill (standalone variant — invokes this
// binary directly, no repo) to ~/.claude/skills/jd-tailored-resume/. Always
// overwrites: re-running --install-skill is the update mechanism, no repo/build
// step, matches this CLI's non-interactive style elsewhere.
function installSkill() {
  const dest = path.join(os.homedir(), ".claude", "skills", "jd-tailored-resume");
  for (const [relPath, content] of Object.entries(SKILL_BUNDLE)) {
    const full = path.join(dest, relPath);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, "utf-8");
    if (relPath.endsWith(".py")) fs.chmodSync(full, 0o755);
  }
  console.log(`✓ Installed jd-tailored-resume skill (standalone variant — uses build-resume directly, no repo) to:`);
  console.log(`  ${dest}`);
  console.log(`  Files: ${Object.keys(SKILL_BUNDLE).join(", ")}`);
}

function readJson(p: string): any {
  return JSON.parse(fs.readFileSync(p, "utf-8"));
}

function resolveThemePath(themeArg: string | undefined, contentTheme: string | undefined, root: string): string | undefined {
  const name = themeArg || contentTheme;
  if (!name) return undefined;
  if (name.endsWith(".json") && fs.existsSync(name)) return name;
  const byName = path.join(root, "themes", `${name}.theme.json`);
  if (fs.existsSync(byName)) return byName;
  if (fs.existsSync(name)) return name;
  return undefined;
}

function printWarnings(label: string, warnings: Warning[] | string[], quiet: boolean) {
  if (quiet || !warnings.length) return;
  console.warn(`\n⚠  ${label} (${warnings.length}):`);
  for (const w of warnings as any[]) {
    if (typeof w === "string") console.warn(`   - ${w}`);
    else console.warn(`   - ${w.path}: ${w.message}`);
  }
}

async function main() {
  const args = parseArgs(process.argv);
  const root = path.resolve(__dirname, "..");

  if (!args.content) { console.error("Error: --content <file.json> is required."); printHelp(); process.exit(2); }
  if (!fs.existsSync(args.content)) { console.error(`Error: content file not found: ${args.content}`); process.exit(2); }

  // --- load + validate content (best-effort) ---
  const content: ResumeContent = readJson(args.content);
  const contentSchema = fs.existsSync(args.schema) ? readJson(args.schema) : resumeSchemaBuiltin;
  let contentWarnings: Warning[] = validate(contentSchema, content);
  printWarnings("Content validation warnings", contentWarnings, args.quiet);

  // --- load + validate theme (best-effort) ---
  // A bare theme name checks the embedded BUILTIN_THEMES first (works with no
  // filesystem access, e.g. inside a compiled binary); only names outside that map,
  // or an explicit --theme <path.json>, fall through to the fs-based lookup.
  const themeName = args.theme || content.theme;
  let themeRaw: Theme = {};
  let themeSource: string | undefined;
  if (themeName && BUILTIN_THEMES[themeName]) {
    themeRaw = BUILTIN_THEMES[themeName];
    themeSource = `${themeName} (built-in)`;
  } else {
    const themePath = resolveThemePath(args.theme, content.theme, root);
    if (themePath) {
      themeRaw = readJson(themePath);
      themeSource = path.basename(themePath);
    } else if (themeName) {
      console.warn(`⚠  Theme "${themeName}" not found; using built-in defaults.`);
    }
  }
  if (themeSource) {
    const themeSchema = fs.existsSync(args.themeSchema) ? readJson(args.themeSchema) : themeSchemaBuiltin;
    const themeWarnings = validate(themeSchema, themeRaw);
    printWarnings(`Theme validation warnings (${themeSource})`, themeWarnings, args.quiet);
    contentWarnings = contentWarnings.concat(themeWarnings);
  }
  const theme = resolveTheme(themeRaw);

  // --- output paths ---
  fs.mkdirSync(args.out, { recursive: true });
  const base = args.basename || sanitize(content.basics?.name || "resume");
  const docxPath = path.join(args.out, `${base}.docx`);
  const runtimeWarnings: string[] = [];

  // --- PDF toolchain preflight (surface missing binaries up front, not just after a failed convert) ---
  const toolchain = (args.pdf || args.autofit) ? checkPdfToolchain() : { soffice: true, pdfinfo: true };
  const toolchainWarning = pdfToolchainWarning(toolchain);
  if (toolchainWarning && (args.pdf || args.autofit)) runtimeWarnings.push(toolchainWarning);

  // --- autofit (optional) ---
  let finalTheme = theme;
  if (args.autofit) {
    if (!args.pdf) {
      runtimeWarnings.push("--one-pager requires PDF rendering to measure pages; ignoring --no-pdf for measurement.");
    }
    const result = await autofitToSinglePage(content, theme, args.keywords);
    finalTheme = result.finalTheme;
    runtimeWarnings.push(...result.warnings);
    if (!args.quiet) {
      console.log(`\n▸ Autofit: ${result.fitted ? "fit to 1 page" : `stopped at ${result.pages} page(s)`} after ${result.iterations} iteration(s).`);
      console.log(`  final: body ${finalTheme.sizeBody}pt · margins ${finalTheme.margins.top}in · line-height ${finalTheme.lineHeight}`);
    }
  }

  // --- render + pack final docx ---
  const { doc, commentCount } = renderResume(content, finalTheme, args.keywords);
  const { commentIdsFixed } = await packDocx(doc, docxPath);
  if (!args.quiet) {
    console.log(`\n✓ DOCX: ${docxPath}`);
    if (commentCount) console.log(`  ${commentCount} flag comment(s)${commentIdsFixed ? `; repaired ${commentIdsFixed} marker id(s)` : ""}.`);
  }

  // --- pdf ---
  if (args.pdf) {
    const pdfPath = convertToPdf(docxPath, args.out);
    const pages = countPdfPages(pdfPath);
    if (fs.existsSync(pdfPath)) {
      if (!args.quiet) console.log(`✓ PDF:  ${pdfPath}${pages > 0 ? `  (${pages} page${pages === 1 ? "" : "s"})` : ""}`);
    } else if (!toolchainWarning) {
      // Toolchain looked present but conversion still failed — a different problem than a missing binary.
      runtimeWarnings.push("PDF conversion failed despite soffice/pdfinfo being on PATH; DOCX was still written. Check LibreOffice logs.");
    }
  }

  printWarnings("Runtime warnings", runtimeWarnings, args.quiet);

  const totalWarnings = contentWarnings.length + runtimeWarnings.length;
  if (args.strict && totalWarnings > 0) {
    console.error(`\n✗ --strict: ${totalWarnings} warning(s); exiting non-zero.`);
    process.exit(1);
  }
}

function sanitize(s: string): string {
  return s.replace(/[^\w.-]+/g, "_").replace(/^_+|_+$/g, "") || "resume";
}

main().catch((e) => { console.error("Fatal:", e); process.exit(1); });
